# Generated by Django 3.0.7 on 2020-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estilo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.TextField(blank=True, null=True)),
                ('requerido', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('columna', models.IntegerField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('general', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('imagen', models.ImageField(upload_to='administracion/imagenes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('menu', models.BooleanField(default=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('id_pagina', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenidos', models.ManyToManyField(through='administracion.Contenido', to='administracion.Etiqueta')),
            ],
        ),
    ]
