# Generated by Django 3.0.7 on 2020-07-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200711_1300'),
        ('web', '0003_producto_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local_Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.Imagen')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Local')),
            ],
        ),
    ]
