# Generated by Django 3.0.7 on 2020-07-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_franquicia_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='inicio',
            field=models.BooleanField(default=False),
        ),
    ]
