# Generated by Django 3.0.7 on 2020-07-14 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20200711_1300'),
        ('web', '0005_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.Imagen'),
            preserve_default=False,
        ),
    ]
